microsoft/devicescript

.github/workflows/docs.yml
.gitignore
compiler/build.js
website/src/remark/compile.js

Move compiled files to /static/dist and also export compiler.js

build compiler into web site

---

cli/package.json
website/docs/DeveloperExperience/architecture.md
website/docs/Language/_category_.json
website/docs/Language/buffers.md
website/docs/Language/cloud.md
website/docs/Language/handlers-and-fibers.md
website/docs/Language/jacscript-subset.md
website/docs/Language/registers.md
website/docs/Language/roles.md
website/docs/Language/top-level-functions.md
website/docs/Language/user-defined-functions.md
website/docs/intro.md
website/docusaurus.config.js
website/package.json
website/src/components/TutorialComponents/index.tsx
website/src/components/TutorialComponents/runJacscript.ts
website/src/css/custom.css
website/src/remark/render-code-blocks.mjs
website/src/theme/Root.jsx
website/yarn.lock
yarn.lock

show jacdac dasboard as split pane

---

jacs/run-tests/basic.ts
jacs/samples/buffer.ts
jacs/samples/buzzer.ts
jacs/samples/cloud-light.ts
jacs/samples/cloud.ts
jacs/samples/commands.ts
jacs/samples/complex.ts
jacs/samples/console.ts
jacs/samples/display-dimmer.ts
jacs/samples/every.ts
jacs/samples/fields.ts
jacs/samples/hid.ts
jacs/samples/hidmouse.ts
jacs/samples/light-dimmer.ts
jacs/samples/light-switch-wait.ts
jacs/samples/light-switch.ts
jacs/samples/pending.ts
jacs/samples/pingpong.ts
jacs/samples/servo1.ts
jacs/samples/thermostat.ts
website/docs/Language/jacscript-subset.md
website/docs/Language/registers.md
website/docs/Language/user-defined-functions.md

move away from `var` in samples; use `const`, `let` instead

Const samples

---

cli/README.md
cli/package.json
cli/src/build.ts
cli/src/cli.ts
website/docs/Dev/cli.md
yarn.lock

Support for watching file in CLI

patch: build --watch

---

cli/src/init.ts
website/language.config.js
website/src/components/TutorialComponents/CodeBlock.tsx
website/src/components/TutorialComponents/CodeSandboxButton.tsx
website/src/components/TutorialComponents/index.tsx
website/src/remark/render-code-blocks.mjs

Add button to open source in codesandbox project

fix: codesandbox support

---

compiler/src/compiler.ts
compiler/src/format.ts
website/docs/Language/buffers.md
website/docs/Language/devicescript-subset.md
website/docs/Language/registers.md
website/docs/Language/user-defined-functions.md
website/docs/developer/getting-started/code.md
website/docs/intro.md
website/src/remark/compile.js

Broken samples should break the build

test breaking build

---

compiler/src/specgen.ts
website/docs/Language/buffers.md
website/docs/Language/devicescript-subset.md
website/docs/Language/registers.md
website/docs/Language/user-defined-functions.md
website/package.json
website/src/contexts/SplitDevTools.jsx
website/src/remark/render-code-blocks.mjs
website/yarn.lock

patch: concurrent execution of compiles

---

compiler/src/specgen.ts
devs/lib/devicescript-core.d.ts

patch: rename registernumber

---

devs/lib/devicescript-core.d.ts
devs/lib/tsconfig-docs.json

A few comments and questions on the TS api

Api comments

---

runtime/devicescript-vm/README.md
runtime/devicescript-vm/dist/types.d.ts
runtime/devicescript-vm/wasmpre.ts
website/docs/api/vm.md

patch: document vm apis

---

vscode/package.json
vscode/src/JDomTreeDataProvider.ts
vscode/src/activateDeviceScript.ts
vscode/src/jacdac.ts

First draft, with a bunch of rough edges, but still a tree.

Device Tree in VS Code

---

website/docusaurus.config.js
website/package.json
yarn.lock

Docusaurus2.3

---

vscode/README.md
vscode/package.json
vscode/src/CloudTreeDataProvider.ts
vscode/src/activateDeviceScript.ts
vscode/src/debugger.ts
vscode/src/devtoolsserver.ts
vscode/src/pickers.ts
vscode/src/simulatorWebView.ts
vscode/src/state.ts
website/src/components/HomepageFeatures/index.tsx

Cleanup refactorings, plus handling no workspace scenarios, multi-root.

fix: better support for empty workspace, remote

---

vscode/package.json
vscode/src/JDomTreeDataProvider.ts
vscode/src/activateDeviceScript.ts

Listen for treeview collapse/expand events and release change subscriptions.

fix: tree unsubscription

---

vscode/package.json
vscode/src/JDomTreeDataProvider.ts
vscode/src/commands.ts
vscode/src/constants.ts

Wifi tree items, cloud adapter

cloud tree items

---

cli/src/build.ts
cli/src/cli.ts
cli/src/command.ts
compiler/src/compiler.ts
compiler/src/format.ts
website/docusaurus.config.js

Options to disable colors which tends to mess up formatting in doc generation.

feat: no-colors mode

---

cli/src/sidedata.ts
cli/src/sideprotocol.ts
vscode/package.json
vscode/src/CloudExtensionState.ts
vscode/src/activateDeviceScript.ts
vscode/src/devtoolsserver.ts
vscode/src/state.ts

flash device as palette command

---

cli/src/devtools.ts
vscode/src/devtoolsserver.ts

Kick a build on load when there's a suitable file.

start building on load extension

---

cli/package.json
compiler/package.json
package.json
runtime/devicescript-vm/package.json
vscode/package.json
vscode/sampleprj/packages/cloud/src/index.ts
vscode/sampleprj/packages/cloud/src/main.ts
vscode/sampleprj/packages/sampleprj/src/cloud.ts
vscode/sampleprj/packages/sampleprj/src/main.ts
vscode/src/gateway/GatewayTreeDataProvider.ts
website/docs/developer/cloud.mdx
yarn.lock

fix: update trackException

---

vscode/README.md
vscode/src/JDomTreeDataProvider.ts
vscode/src/activateDeviceScript.ts
vscode/src/commands.ts
vscode/src/constants.ts
vscode/src/debugger.ts
vscode/src/deploy.ts
vscode/src/devtoolsserver.ts
vscode/src/gateway/GatewayExtensionState.ts
vscode/src/state.ts
vscode/src/telemetry.ts

Collect ticks when things go wrong

use telemetry for showError messages

---

vscode/package.json
vscode/sampleprj/packages/i2c/src/main.ts
vscode/src/activateDeviceScript.ts
vscode/src/pickers.ts
vscode/src/state.ts

50% through, it configures the board.
Need to gather the server info to add another drop down.

Configure hw

---

vscode/sampleprj/packages/i2c/src/api.ts
vscode/sampleprj/packages/i2c/src/client.ts
vscode/sampleprj/packages/i2c/src/index.ts
vscode/sampleprj/packages/i2c/src/main.ts
vscode/sampleprj/packages/sampleprj/src/aht20.ts

@tballmsft  can you try this modified i2c sample? i need the hardware to test this (or maybe i need a simulator).

use observable streams instead

---

cli/src/cli.ts
cli/src/command.ts
vscode/package.json
vscode/src/devtoolsserver.ts

Adds cli and vscode setting to turn on developer mode to allow using other boards.

Developer mode

---

packages/sampleprj/src/gpiorelay.ts
packages/server/src/sensor.ts
packages/server/src/servercore.ts

- a bit more meat in server base class
- treat undefined as not implemented
- sample of gpio relay service

Minor server refactorings

---

devs/run-tests/basic.ts
packages/drivers/src/aht20.ts
packages/drivers/src/driver.ts
packages/drivers/src/index.ts
packages/drivers/src/sht.ts
packages/drivers/src/sht30.ts
packages/drivers/src/shtc3.ts
packages/i2c/src/client.ts
packages/i2c/src/index.ts

A more structured way to creating i2c driver, and jacdac servers. Probably need to be tweaked for roles updates. @mmoskal

I2c driver

---

build.js
compiler/src/compiler.ts
packages/drivers/src/index.ts
packages/sampleprj/src/main.ts

More descriptive function name.

hardwareConfig -> configureHardware ?

---

cli/src/init.ts

Initial support for Yarn v2+
https://yarnpkg.com/getting-started/migration

support for yarn 2.0

---

CONTRIBUTING.md

Just a typo fix in CONTRIBUTING.md
Looking forward to work more on this project.

Typo fix in CONTRIBUTING.md

---

cli/src/cli.ts
cli/src/deploy.ts
cli/src/devtools.ts
cli/src/init.ts
cli/src/run.ts
cli/src/sideprotocol.ts
compiler/src/compiler.ts
compiler/src/dotenv.ts
packages/i2c/.gitignore
packages/sampleprj/.env.defaults
packages/sampleprj/.gitignore
packages/sampleprj/src/mainenv.ts
packages/settings/src/client.ts
vscode/package.json
vscode/src/JDomTreeDataProvider.ts
vscode/src/activateDeviceScript.ts
vscode/src/state.ts
website/docs/developer/settings.mdx

support for .env file

---

website/docs/getting-started/cli.mdx

Fix trivial typo in CLI docs

---

cli/src/cli.ts
cli/src/flash.ts
vscode/src/state.ts

When esptool is missing, auto-install esptool from vscode

auto install esptool on flash

---

cli/src/init.ts
vscode/src/devtoolsserver.ts

don't use yarn

---

packages/runtime/src/control.ts
packages/sampleprj/src/mainmcutemperature.ts
website/docs/developer/mcu-temperature.mdx

mcu_temperature support. https://microsoft.github.io/jacdac-docs/services/control/

mcuTemperature API + docs

---

cli/src/deploy.ts
website/docs/developer/settings.mdx
website/docs/getting-started/samples/adafruit-io-feed.mdx

Support setting the WiFI SSID and password through the settings file.
Updated adafruit guide.

Wifi settings

---

packages/sampleprj/src/mainblynk.ts
packages/sampleprj/src/mainesp32oled.ts

- basic blynk support using http requests

blynk HTTP support

---

packages/drivers/src/characterscreen.ts
packages/graphics/src/canvas.ts
packages/graphics/src/image.ts
website/docs/api/servers/ssd1306.mdx

ImageRenderingContext

---

website/docs/developer/servers/index.mdx

Nothing special here, just cleanups.

Misc word/grammar fixes to index.mdx

---

packages/observables/src/main.ts
packages/observables/src/transform.ts
website/docs/api/observables/transform.mdx

https://github.com/microsoft/devicescript/discussions/479

support for switchMap in observables

---

website/docs/getting-started/cli.mdx

Just small fix as my first contribution to this project.

Fixing spelling in getting started

---

devs/run-tests/24arraymap.ts
packages/core/src/array.ts
packages/core/src/corelib.d.ts

Implemented https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill
https://github.com/microsoft/devicescript/issues/503

added array fill

---

devs/run-tests/24arraymap.ts
packages/core/src/array.ts
packages/core/src/corelib.d.ts

Implemented https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findLast
https://github.com/microsoft/devicescript/issues/503

array findLast

---

devs/run-tests/24arraymap.ts
packages/core/src/array.ts
packages/core/src/corelib.d.ts

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findLastIndex
https://github.com/microsoft/devicescript/issues/503

Added findLastIndex

---

.github/ISSUE_TEMPLATE/bug_report.md
cli/src/init.ts
interop/src/constants.ts
vscode/package.json
vscode/src/activateDeviceScript.ts
vscode/src/devtoolsserver.ts

Will come handy to ensure tools are up to date.
- upgrade report issue...

add command to upgrade tools

---

devs/run-tests/24arraymap.ts
packages/core/src/array.ts
packages/core/src/corelib.d.ts

Implemented https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
#599

Array sort

---

cli/src/build.ts
scripts/processvideos.mjs

Hi, this PR aims to achieve a very minor performance improvement by running async functions concurrently using `Promise.all`. This enhancement will improve performance and effectively utilize hardware resources.

Optimizing Performance and Resource Utilization Through Concurrent Async Execution ✈

---

packages/runtime/src/main.ts
packages/runtime/src/number.ts

I've added Number.isNaN core js function

Added Number.isNaN

---

compiler/src/boards.json
packages/drivers/src/kittenbotgrapebit.ts
packages/sampleprj/src/maingrapebit.ts
website/docs/devices/boards.json
website/docs/devices/esp32/kittenbot-grapebit-esp32c3.mdx

1. correct motor pin define
2. missing imu driver init
3. rgb led as jd service
All modification tested over real hardware.

Grapebit fixes

---

devs/run-tests/24arraymap.ts
packages/core/src/array.ts
packages/core/src/corelib.d.ts

Added array reverse
