cli/package.json
cli/src/build.ts
cli/src/cli.ts
cli/src/command.ts
cli/src/tsconfig.json
compiler/build.js
yarn.lock

Refactor cli to support multiple commands

cleaning up cli

---

compiler/package.json

The devicescript-compiler does not contain any built files.

patch: specify to embed built files in package

---

cli/package.json
compiler/src/compiler.ts
runtime/devicescript-vm/runner.js

patch: rename generate compiler files

---

runtime/devicescript-vm/wasmpre.ts

Pull in jacdac-c version
(note: because of the folder structure, updating jacdac-c does not automatically trigger a npm package update, so we somehow need to trigger a change under devicescript-vm)

patch: support for runtime_version

---

cli/src/build.ts
cli/src/cli.ts
cli/src/devtools.ts
cli/src/init.ts
vscode/sampleprj/package.json
website/docs/api/cli.md
website/docs/getting-started/code.md
website/docusaurus.config.js

Use devtools instead of build --watch.
@mmoskal should we ask for a filename to turn on watch?

fix: update cli info about build --watch

---

cli/src/vmworker.ts

The worker may hang for a number of reasons, stop should be increasingly aggressive at killing it.
- consider using 'tree-kill' package as well

more aggressive about killing worker

---

cli/src/devtools.ts
cli/src/vmworker.ts

Always stop the vm when a debugging session ends.

fix: stop vm worker on debug session close

---

vscode/src/debugger.ts
vscode/src/devtoolsserver.ts
vscode/src/mainstatusbar.ts
vscode/src/state.ts

vscode has builtin support to spin off file system watchers, using instead of native cli watchers.

fix: use vscode built-in file system watcher

---

devs/compiler-tests/toplevel.ts
devs/lib/clientcmds.ts
devs/lib/devicescript-core.d.ts
devs/samples/display-dimmer.ts
devs/samples/servo1.ts
devs/samples/thermostat.ts
package.json

Cleaning out the role.connected code. The only thing left is "isConnected" which will need to be patched on the c++.

fix: cleaning out role.connected

---

website/docs/getting-started/samples/homebridge-humidity.mdx

The PR contains a simple fix to the HomeBridge broken hyperlink found in the docs.

docs: fix broken HomeBridge hyperlink

---

compiler/src/compiler.ts
compiler/src/serverinfo.ts
compiler/src/specgen.ts
devs/run-tests/basic.ts
packages/drivers/src/aht20.ts
packages/drivers/src/bme680.ts
packages/drivers/src/ltr390.ts
packages/drivers/src/sht30.ts
packages/drivers/src/shtc3.ts
website/docs/language/tree-shaking.mdx

Turns out that VSCode really wants camelized names to colorize the jsdoc attributes.

tsdoc attributes normalization

---

packages/net/src/fetch.ts
packages/net/src/sockets.ts
packages/sampleprj/src/mainsockets.ts
website/docs/developer/net.mdx

Better docs on sockets
move Socket.connect to just "connect" to match node.

added socket example, use same api as node

---

packages/net/src/fetch.ts

port parsing was broken due to host being reassigned first

fix port parsing

---

cli/src/init.ts
compiler/src/compiler.ts
website/docs/developer/packages/custom.mdx

When adding npm to a package, drop files to enable proper generation of TypeDoc web site.
- example: https://pelikhan.github.io/devicescript-pico-bricks

support for typedoc ready projects

---

cli/src/cli.ts
cli/src/init.ts
vscode/src/activateDeviceScript.ts
vscode/src/pickers.ts
vscode/src/state.ts
website/docs/api/cli.mdx
website/docs/developer/console.mdx

Add choosing board id in "create new project" flow to avoid missing the pin configuration step.
- also reduce number of recommended extensions

project init (create new project) with board

---

runtime/devicescript/impl_ds.c

Send user-defined server device instead main device id in twin message packet.

use server id in twin message

---

website/src/components/DeviceCard/index.tsx
website/src/components/HeroImage/index.tsx
website/src/components/KeyGenerator/index.tsx

Hi, this PR introduces a small improvement to the website.
1. By wrapping a function in `useCallback`, you gain the advantage of optimizing performance and reducing unnecessary re-renders in your React components.
2. Adding the `decoding="async"` HTML attribute to the image tag provides the benefit of improving the page's loading speed by allowing the browser to start decoding the image as soon as possible without blocking other page rendering tasks.

Performance and Loading Speed Enhancements for the Website 🏎

---

cli/src/build.ts
cli/src/cli.ts
cli/src/command.ts
cli/src/devtools.ts
cli/src/exec.ts
cli/src/init.ts
cli/src/logging.ts
cli/src/packageinstaller.ts
cli/src/prompt.ts
cli/src/transport.ts
interop/src/archconfig.ts

Moved a few things around to match https://github.com/microsoft/devicescript/pull/653 from @dawiidio

Update PR for https://github.com/microsoft/devicescript/pull/653

---

vscode/src/devtoolsserver.ts

The warning says 16+ is required, when actually 20+ is required. I had 18 and was very confused with the warning until I looked at the source code.

Update node version warning in devtoolsserver.ts

---

website/docs/getting-started/vscode/index.mdx

20+ is actually required, not 16. I also updated the warning in code with this other PR: https://github.com/microsoft/devicescript/pull/680

Update docs on required node version

---

vscode/src/devtoolsserver.ts

Hello
This PR is only to remove an unnecessary use of node to run a bash script.
In Linux the extension is trying to run the development Server using the Node runtime, but the file chosen is written in Bash script.
Since I don't own any Windows Device to test (for now), I just removed the use of Node for Linux

Removed unnecessary use of node to run a bash script
